### PR TITLE
fix: don't remove package.json bin in migration

### LINKED ISSUE #797: 🐛 Bug: Respect existing package.json bins during migration
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Discovered working on https://github.com/JoshuaKGoldberg/should-semantic-release/issues/100: running `npx create-typescript-app --mode migrate` will remove the `bin` entry from a `package.json`. But it shouldn't. Some packages have that entry intentionally.

### Additional Info

I originally filed this as a feature, but on second thought it's really a bug.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #797
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This is now the second piece of conditional logic in `updateLocalFiles`, so I switched its config parameter to directly take in `mode: Mode`.

This particular change also finally got its snapshot tests past my personal _"tl;dr"_ threshold. I switched the logic based on `logic` to use more targeted `toHaveBeenCalledWith`s instead.

### CODE REVIEW

File: src/steps/updateLocalFiles.ts [hunk 1]
```diff
@@ -8,10 +9,7 @@ interface ExistingPackageData {
 	version?: string;
 }
 
-export async function updateLocalFiles(
-	options: Options,
-	config = { resetPackageVersion: false },
```
Comment (JoshuaKGoldberg) [inline src/steps/updateLocalFiles.ts:13]: Just a heads up @nowyDEV. No complaints about having the `config` in #846. Just seeing more new logic for this function now.
