### PR TITLE
fix: preserve package version during migration

### LINKED ISSUE #798: 🐛 Bug: migration overrides package.json version
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

When running `npx create-typescript-app --mode migrate`, if `package.json` already has a `version` property, it should remain the same.

### Actual

Migration is setting it to `0.0.0` always 😞 

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by nowyDEV**
## PR Checklist

- [x] Addresses an existing open issue: fixes #798
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Added additional config parameter to `updateLocalFiles`, so we can skip overwriting package version inside migrate script.

### CODE REVIEW

File: src/steps/updateLocalFiles.ts [hunk 1]
```diff
@@ -8,7 +8,10 @@ interface ExistingPackageData {
 	version?: string;
 }
 
-export async function updateLocalFiles(options: Options) {
+export async function updateLocalFiles(
+	options: Options,
+	config = { resetPackageVersion: false },
```
Comment (nowyDEV) [inline src/steps/updateLocalFiles.ts:13]: I've assumed we don't want to add another option for the user (extend `options`) and opted for a fully internal solution utilizing additional parameter).

Comment (JoshuaKGoldberg) [reply src/steps/updateLocalFiles.ts:13]: Yeah I think that makes sense. 👍

**Review by JoshuaKGoldberg — APPROVED** [review]
Super, no notes - thanks! 🔥
