### PR TITLE
fix: improve migration owner replacements

### LINKED ISSUE #1043: 🐛 Bug: Migrating a non-JoshuaKGoldberg repo creates the wrong owners for JoshuaKGoldberg actions
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Running `--mode migrate` on an existing repo under a owner other than `JoshuaKGoldberg` should still set up actions like `JoshuaKGoldberg/release-it-action` under the proper owners.

### Actual

I'd missed in https://github.com/omnidan/node-emoji/pull/142 that two actions were set up incorrectly:

* `omnidan/all-contributors-auto-action` was configured instead of `JoshuaKGoldberg/all-contributors-auto-action`
* `omnidan/release-it-action` was configured instead of `JoshuaKGoldberg/release-it-action`

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1043
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Uses a [`to` callback](https://github.com/adamreisnz/replace-in-file/#using-callbacks-for-to) to determine whether to swap out owner to `options.owner` in `"JoshuaKGoldberg"` _(always)_ or `"JoshuaKGoldberg/..."` (if the `...` is `options.repository`).

Also fixes some existing edge cases around owner replacements:

* Syncs up the end-of-readme attribution notice so there's only one place it's written in the templates
* Uses `options.owner` and `options.repository` in `createDotGitHubFiles` instead of hardcoding `JoshuaKGoldberg/create-typescript-app`.

### CODE REVIEW

File: src/steps/updateLocalFiles.ts [hunk 1]
```diff
@@ -14,7 +15,19 @@ export async function updateLocalFiles(options: Options) {
...
+				capture
+					? // If this was a "JoshuaKGoldberg/..." repository link,
+					  // swap the owner if it's the repository being migrated.
+					  capture.startsWith(options.repository)
+						? `${options.owner}/${capture}`
+						: full
+					: // Otherwise it's just "JoshuaKGoldberg" standalone,
+					  // so swap to the new owner.
+					  options.owner,
+		],
```
Comment (JoshuaKGoldberg) [inline src/steps/updateLocalFiles.ts:30]: I'd sure love to unit test this. Blocked on https://github.com/adamreisnz/replace-in-file/issues/175, I think.

Comment (JoshuaKGoldberg) [reply src/steps/updateLocalFiles.ts]: Sort of tested in https://github.com/JoshuaKGoldberg/create-typescript-app/pull/1078/commits/67a31169ce652825989e4f2dcbe7cfa5a0334eb7. It's not ideal. Blocked on doing better with either using a virtual file system as I'd proposed, or more fully mocking out fs.
