### PR TITLE
fix: handle subset file matches in blockPackageJson

### LINKED ISSUE #2106: 🐛 Bug: package.json files should deduplicate clear directory subsets
### Bug Report Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have pulled the latest `main` branch of the repository.
- [x] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

If `blockPackageJson` is being told to print:

```json
"files": [
	"LICENSE.md",
	"README.md",
	"lib/",
	"lib/bin/pjv.mjs"
]
```

...then it should know to remove `"lib/bin/pjv.mjs"`. It's clearly matched by the earlier `"lib/"`.

### Actual

https://github.com/JoshuaKGoldberg/package-json-validator/pull/178/files#r2024966892 shows that this is not the case right now.

### Additional Info

🎁

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #2106
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

🎁

### CODE REVIEW

File: src/blocks/blockPackageJson.ts [hunk 1]
```diff
@@ -59,16 +59,13 @@ export const blockPackageJson = base.createBlock({
...
 								...collectBinFiles(options.bin),
 								...(addons.properties.files ?? []),
 								"package.json",
 								"README.md",
-							]
-								.filter(Boolean)
-								.sort(),
+							]),
 							keywords: options.keywords,
-							license: "MIT",
```
Comment (JoshuaKGoldberg) [inline src/blocks/blockPackageJson.ts:71]: I couldn't resist while I was here, heh. This is provided by `blockMITLicense`.
