### PR TITLE
fix: don't suggest redundant --directory

### LINKED ISSUE #1126: 🐛 Bug: Re-run command suggestion includes unnecessary --directory
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

I ran `npx create-typescript-app --mode create --base everything` and filled in all the options. At the end, it should have suggested a re-run command that:

* Included `--base everything` and `--mode create`
* Filled in values I provided in the prompt...
* ...and _not_ values implied by `--base everything` or `--mode create`

### Actual

This was the suggestion it printed:

```plaintext
●  Tip: to run again with the same input values, use: npx create-typescript-app --mode create --base everything --access public --description "Hooray. Delete." --directory delete-me-please --email-github git@joshuakgoldberg.com --email-npm npm@joshuakgoldberg.com --mode create --owner JoshuaKGoldberg --repository delete-me-please --title "Delete Me Please"
```

Note the `--directory delete-me-please`. That's implied by `--repository delete-me-please`. There's no need to print `--directory` if it's got the same value as `--repository`. Bug!

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1126
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

💖

### CODE REVIEW

File: src/create/createRerunDirectorySuggestion.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { Options } from "../shared/types.js";
+
+export function createRerunDirectorySuggestion(options: Partial<Options>) {
+	if (!options.directory) {
+		return undefined;
+	}
+
```
Comment (JoshuaKGoldberg) [inline src/create/createRerunDirectorySuggestion.ts:7]:
```suggestion
```
